In [32]:
# Delete the record
import sqlite3
try:
    connection.execute("DELETE FROM student11 WHERE stud_roll = 1;")
    connection.commit()
    print("Total number of rows deleted:",connection.total_changes)
    cursor = connection.execute("SELECT stud_roll,stud_name from student11")
    for row in cursor:
        print("Student Roll = ",row[0])
        print("Student Name = ",row[1],"\n")
except sqlite3.Error as se:
    print("Error(s) occured....")
finally:
    print("Data updated successfully....")
    connection.close()

Data updated successfully....


NameError: ignored

In [33]:
# Machine Learning

import numpy as np

data1 = [1, 2, 3, 4, 5] # Creating a list
arr1 = np.array(data1) # Creating a 1d array from list
data1

[1, 2, 3, 4, 5]

In [34]:
arr1

array([1, 2, 3, 4, 5])

In [0]:
data2 = [range(1,5),range(5,9)]

In [36]:
data2

[range(1, 5), range(5, 9)]

In [0]:
arr2 = np.array(data2)

In [38]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
arr2.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [40]:
arr1.dtype

dtype('int64')

In [41]:
arr2.ndim

2

In [42]:
arr2.size

8

In [43]:
len(arr2)

2

In [44]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.zeros((3,6),int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [46]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [47]:
np.diag([11,22,33,44,55])

array([[11,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0],
       [ 0,  0, 33,  0,  0],
       [ 0,  0,  0, 44,  0],
       [ 0,  0,  0,  0, 55]])

In [48]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [49]:
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

In [50]:
np.logspace(0,3,4,base=2)

array([1., 2., 4., 8.])

In [51]:
int_array = np.arange(5)
print(int_array)
float_array = int_array.astype(float)

[0 1 2 3 4]


In [52]:
float_array

array([0., 1., 2., 3., 4.])

In [53]:
int_array

array([0, 1, 2, 3, 4])

In [54]:
matrix = np.arange(10,dtype=float) # Reshaping
matrix

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [55]:
matrix.shape

(10,)

In [0]:
matrix = matrix.reshape(5,2)

In [57]:
matrix

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [58]:
matrix.shape

(5, 2)

In [59]:
matrix.T

array([[0., 2., 4., 6., 8.],
       [1., 3., 5., 7., 9.]])