In [1]:
# Database operation
# 1. Create a database and create a table
import sqlite3

connection = sqlite3.connect('testAA.db')
print("Opened database successfully....")
connection.execute('''CREATE TABLE student11
                   (stud_roll INTEGER PRIMARY KEY NOT NULL,
                   stud_name TEXT);''')
print("Table created successfully....")
# connection.close()

Opened database successfully....
Table created successfully....


In [2]:
# 2. Insert data into the table

connection = sqlite3.connect('testAA.db')
print("Opened database successfully....")
connection.execute("INSERT INTO student11(stud_roll,stud_name)\
VALUES(1,'Abcd')");
connection.execute("INSERT INTO student11(stud_roll,stud_name)\
VALUES(2,'Efgh')");
connection.commit()
print("Records created successfully....")
# connection.close()

Opened database successfully....
Records created successfully....


In [3]:
# 3. Display the data from the table
   
cursor = connection.execute("SELECT stud_roll,stud_name from student11")
for row in cursor:
    print("Student Roll = ",row[0])
    print("Student Name = ",row[1],"\n")
print("Data displayed successfully....")
# connection.close()

Student Roll =  1
Student Name =  Abcd 

Student Roll =  2
Student Name =  Efgh 

Data displayed successfully....


In [4]:
# 4. Update the record
cursor = connection.execute("UPDATE student11 set stud_name = 'Avik' where stud_roll = 1")
print("Total number of rows updated:",connection.total_changes)
cursor = connection.execute("SELECT stud_roll,stud_name from student11")
for row in cursor:
    print("Student Roll = ",row[0])
    print("Student Name = ",row[1],"\n")
print("Data updated successfully....")
# connection.close()

Total number of rows updated: 3
Student Roll =  1
Student Name =  Avik 

Student Roll =  2
Student Name =  Efgh 

Data updated successfully....


In [5]:
# Delete the record
try:
    connection.execute("DELETE FROM student11 WHERE stud_roll = 1;")
    connection.commit()
    print("Total number of rows deleted:",connection.total_changes)
    cursor = connection.execute("SELECT stud_roll,stud_name from student11")
    for row in cursor:
        print("Student Roll = ",row[0])
        print("Student Name = ",row[1],"\n")
except sqlite3.Error as se:
    print("Error(s) occured....")
finally:
    print("Data updated successfully....")
    connection.close()

Total number of rows deleted: 4
Student Roll =  2
Student Name =  Efgh 

Data updated successfully....


In [6]:
import numpy as np

data1 = [1, 2, 3, 4, 5] # Creating a list
arr1 = np.array(data1) # Creating 1d array from list
data1

[1, 2, 3, 4, 5]

In [7]:
arr1

array([1, 2, 3, 4, 5])

In [0]:
data2 = [range(1,5),range(5,9)] # Creating a list of lists

In [9]:
data2

[range(1, 5), range(5, 9)]

In [0]:
arr2 = np.array(data2)

In [11]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [13]:
arr1.dtype

dtype('int64')

In [14]:
arr2.ndim

2

In [15]:
arr2.size

8

In [16]:
len(arr2)

2

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,6),int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [19]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
np.diag([11,22,44,55,33])

array([[11,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0],
       [ 0,  0, 44,  0,  0],
       [ 0,  0,  0, 55,  0],
       [ 0,  0,  0,  0, 33]])

In [21]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

In [23]:
np.logspace(0,3,4,base=2)

array([1., 2., 4., 8.])

In [24]:
int_array = np.arange(5)
print(int_array)
float_array = int_array.astype(float)

[0 1 2 3 4]


In [25]:
float_array

array([0., 1., 2., 3., 4.])

In [26]:
int_array

array([0, 1, 2, 3, 4])

In [27]:
matrix = np.arange(10,dtype=float) # Reshaping
matrix

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
matrix.shape

(10,)

In [0]:
matrix = matrix.reshape(5,2)

In [30]:
matrix

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [31]:
matrix.shape

(5, 2)

In [32]:
matrix.T

array([[0., 2., 4., 6., 8.],
       [1., 3., 5., 7., 9.]])

In [33]:
arr2 # Slicing operation

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
arr2[0,:]

array([1, 2, 3, 4])

In [35]:
arr2[:,0]

array([1, 5])

In [36]:
arr2[:,:2]

array([[1, 2],
       [5, 6]])

In [37]:
arr2[:,2:]

array([[3, 4],
       [7, 8]])

In [38]:
arr = np.arange(10) # Creating views and copies
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5:8] = 200
arr

array([  0,   1,   2,   3,   4, 200, 200, 200,   8,   9])

In [40]:
arr_view = arr[5:8]
arr_view

array([200, 200, 200])

In [41]:
arr_view[1]=500
arr_view

array([200, 500, 200])

In [42]:
arr

array([  0,   1,   2,   3,   4, 200, 500, 200,   8,   9])

In [43]:
arr_copy = arr[5:8].copy()
arr_copy

array([200, 500, 200])

In [44]:
arr_copy[1] = 1000
arr_copy

array([ 200, 1000,  200])

In [45]:
arr

array([  0,   1,   2,   3,   4, 200, 500, 200,   8,   9])

In [46]:
arr[arr > 5]

array([200, 500, 200,   8,   9])

In [47]:
arr[arr > 5] = 100
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [48]:
names = np.array(["bob","joe","will","bob"])
names == "bob"

array([ True, False, False,  True])

In [49]:
nums = np.arange(5)
nums

array([0, 1, 2, 3, 4])

In [50]:
nums * 10

array([ 0, 10, 20, 30, 40])

In [51]:
nums = np.sqrt(nums)
nums

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [52]:
np.ceil(nums)

array([0., 1., 2., 2., 2.])

In [53]:
np.isnan(nums)

array([False, False, False, False, False])

In [54]:
nums = np.arange(5)
print(nums)
nums = nums + np.arange(5)
nums

[0 1 2 3 4]


array([0, 2, 4, 6, 8])