In [ ]:
# Delete the record
try:
    connection.execute("DELETE FROM student11 WHERE stud_roll = 1;")
    connection.commit()
    print("Total number of rows deleted:",connection.total_changes)
    cursor = connection.execute("SELECT stud_roll,stud_name from student11")
    for row in cursor:
        print("Student Roll = ",row[0])
        print("Student Name = ",row[1],"\n")
except sqlite3.Error as se:
    print("Error(s) occured....")
finally:
    print("Data updated successfully....")
    connection.close()

In [1]:
# Machine Learning

import numpy as np

data1 = [1, 2, 3, 4, 5] # Creating a list
arr1 = np.array(data1) # Creating a 1d array from list
data1

[1, 2, 3, 4, 5]

In [2]:
arr1

array([1, 2, 3, 4, 5])

In [3]:
data2 = [range(1,5),range(5,9)]

In [4]:
data2

[range(1, 5), range(5, 9)]

In [5]:
arr2 = np.array(data2)

In [6]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [8]:
arr1.dtype

dtype('int32')

In [9]:
arr2.ndim

2

In [10]:
arr2.size

8

In [11]:
len(arr2)

2

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,6),int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [16]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
np.diag([11,22,33,44,55])

array([[11,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0],
       [ 0,  0, 33,  0,  0],
       [ 0,  0,  0, 44,  0],
       [ 0,  0,  0,  0, 55]])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

In [20]:
np.logspace(0,3,4,base=2)

array([1., 2., 4., 8.])

In [22]:
int_array = np.arange(5)
print(int_array)
float_array = int_array.astype(float)

[0 1 2 3 4]


In [23]:
float_array

array([0., 1., 2., 3., 4.])

In [24]:
int_array

array([0, 1, 2, 3, 4])

In [25]:
matrix = np.arange(10,dtype=float) # Reshaping
matrix

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
matrix.shape

(10,)

In [27]:
matrix = matrix.reshape(5,2)

In [28]:
matrix

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [29]:
matrix.shape

(5, 2)

In [30]:
matrix.T

array([[0., 2., 4., 6., 8.],
       [1., 3., 5., 7., 9.]])