In [6]:
import numpy as np
matrix1=np.ones((5,2))
print(matrix1)
print()
print()
matrix0=np.zeros((5,2))
print(matrix0)
print()
print()
matrix=np.array([[1,2],[3,4],[5,6],[7,8],[9,0]])
print(matrix)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [3]:
import pandas as pd
cols = ["name","age","gender","job"]
cols
user1 = pd.DataFrame([["Alice",19,"f","student"],["john",26,"m","student"]],columns =cols)

user1

name  age gender      job
0  Alice   19      f  student
1   john   26      m  student