In [8]:
#1.	Write the code to implement linspace and logspace functions.

In [9]:
cols = ["name","age","gender","job"]
cols

['name', 'age', 'gender', 'job']

In [2]:
import numpy as np
np.diag([11,22,33,44,55,])

array([[11,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0],
       [ 0,  0, 33,  0,  0],
       [ 0,  0,  0, 44,  0],
       [ 0,  0,  0,  0, 55]])

In [5]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

In [ ]:
#2.	Create a data frame with some items and and keep one condition to check age is less then 20.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
cols = ["name","age","gender","job"]
cols

['name', 'age', 'gender', 'job']

In [12]:
user1 = pd.DataFrame([["alice",19,"f","student"],["john",26,"m","student"]],columns = cols)

In [13]:
user1

name  age gender      job
0  alice   19      f  student
1   john   26      m  student

In [14]:
a_boolean = user1.age < 20
a_boolean

0     True
1    False
Name: age, dtype: bool