In [ ]:
#1.	Write the code to create a 5X2 matrix

In [6]:
import numpy as np
matrix1=np.ones((5,2))
print(matrix1)
print()
print()
matrix0=np.zeros((5,2))
print(matrix0)
print()
print()
matrix=np.array([[1,2],[3,4],[5,6],[7,8],[9,0]])
print(matrix)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [ ]:
#2.	Create a data frame of 4 attributes.


In [7]:
import pandas as pd
cols = ["name","age","gender","job"]
cols
user1 = pd.DataFrame([["Alice",19,"f","student"],["john",26,"m","student"]],columns cols)

user1



SyntaxError: invalid syntax (<ipython-input-7-e3eb5edfee0c>, line 4)