In [1]:
import numpy as np
matrix1=np.ones((5,2))
print(matrix1)
print()
matrix2=np.zeros((5,2))
print(matrix2)
print()
matrix=np.array([[1,2],[3,4],[5,6],[7,8],[9,0]])
print(matrix)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [3]:
import pandas as pd
cols=["Name","Gender","Age","Job"]
cols
user1=pd.DataFrame([["Shiya","F","8","Student"],["Shom","M","16","Manager"]])
user1

0  1   2        3
0  Shiya  F   8  Student
1   Shom  M  16  Manager