In [4]:
# question no. 1
import numpy as np
mat = np.diag([11,22,33,44])
print(mat)

[[11  0  0  0]
 [ 0 22  0  0]
 [ 0  0 33  0]
 [ 0  0  0 44]]


In [9]:
import pandas as pd
try:
    salary = pd.read_csv("d:/CSV/salary_table.csv")
except:
    url = "https://raw.github.com/duchesnay/pylearn-doc/master/data/salary_table.csv"
    salary = pd.read_csv(url)
df = salary
print(df)

    salary  experience education management
0    13876           1  Bachelor          Y
1    11608           1      Ph.D          N
2    18701           1      Ph.D          Y
3    11283           1    Master          N
4    11767           1      Ph.D          N
5    20872           2    Master          Y
6    11772           2    Master          N
7    10535           2  Bachelor          N
8    12195           2      Ph.D          N
9    12313           3    Master          N
10   14975           3  Bachelor          Y
11   21371           3    Master          Y
12   19800           3      Ph.D          Y
13   11417           4  Bachelor          N
14   20263           4      Ph.D          Y
15   13231           4      Ph.D          N
16   12884           4    Master          N
17   13245           5    Master          N
18   13677           5      Ph.D          N
19   15965           5  Bachelor          Y
20   12336           6  Bachelor          N
21   21352           6      Ph.D